services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    Psr\Log\LoggerAwareInterface:
      tags:
      - name: monolog.logger
        channel: 'antispam'

  Omines\AntiSpamQuarantineBundle\:
    resource: '../src'
